### ISSUE TITLE
nijigen 皮肤修改

### ISSUE THREAD

**Issue by Vanessa219** [88250/solo#115]
https://hacpai.com/article/1588214694429

**Comment by jackzhujie** [comment]
昨天社区的问题是我提的，感谢大佬的及时跟进，但是我今天早上更新镜像之后。问题依然没有解决（已经清理了缓存）。因为电脑端无法重新，只有手机端才能重新，但手机端又不太好看到调试日志。
你可以在手机上打开我的博客看看。
[博客地址](http://blog.aizhifou.cn/)
翻到第二页就能重现问题。

**Comment by 88250** [comment]
收到，稍后我们继续调查。

**Comment by Vanessa219** [comment]
@jackzhujie 我这里已经没有重现了。你再试试。

**Comment by jackzhujie** [comment]
@Vanessa219 刚我仔细测试了一下，我在安卓的微信浏览器，和手机自带的浏览器打开有问题（包括夸克浏览器），用安卓版的chrome浏览器打开没问题。

**Comment by Vanessa219** [comment]
是不是 qq 和微信的缓存，我用的 qq 和微信直接打开是可以的。因为我以前没有访问过你的网站。

**Comment by jackzhujie** [comment]
> 是不是 qq 和微信的缓存，我用的 qq 和微信直接打开是可以的。因为我以前没有访问过你的网站。

你有翻到第二页吗？第二页才会出问题，不是缓存，我换了个新浏览器也会这样，第二页数据就不翻转过来了

**Comment by Vanessa219** [comment]
是的。小米手机是可以的，你的手机是？
[1588309179899804.mp4.zip](https://github.com/88250/solo/files/4562547/1588309179899804.mp4.zip)

**Comment by jackzhujie** [comment]
> 是的。小米手机是可以的，你的手机是？
> [1588309179899804.mp4.zip](https://github.com/88250/solo/files/4562547/1588309179899804.mp4.zip)

好的，你们的没问题就好

**Comment by 88250** [comment]
@jackzhujie 老铁，我们的没问题没用啊，麻烦再帮忙观察一下，如果还有问题继续反馈就行，谢谢。
