### ISSUE TITLE
solo后台评论管理数据显示不全

### ISSUE THREAD

**Issue by Leif160519** [88250/solo#118]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

solo后台评论管理数据显示不全，新评论的内容没有同步到评论管理中

solo后台评论管理页面，最新评论日期为2020年3月26日
![image](https://user-images.githubusercontent.com/19452903/81135088-5b1adc80-8f89-11ea-9f6b-fc31fda2b49a.png)

这是五天前的评论，在后台评论管理页面里却并没有看到
![image](https://user-images.githubusercontent.com/19452903/81135093-5e15cd00-8f89-11ea-82d0-14a38d4863ab.png)

**Comment by 88250** [comment]
感谢反馈，逻辑是这样的：博客端的评论管理只能管理本地评论（没有同步社区的）；文章同步到社区以后评论系统就自动切换为社区评论系统了，内容由社区统一管理了，不会进入本地评论系统。

**Comment by Leif160519** [comment]
了解了
