### ISSUE TITLE
为主题增加下载中心实现在线下载与安装

### ISSUE THREAD

**Issue by vcjmhg** [88250/solo#121]
### 使用的场景

在使用solo过程中，深感挂载`自定义主题`的不便。而且随着solo版本的升级自己以前改的一些主题有极大可能出现不兼容的情况

### 可行的解决方案
希望可以增加一个在线的主题中心，这样各个主题作者可以将自己制作的博客主题发布到主题中心供其他用户下载。类似于`WordPress`
![image](https://user-images.githubusercontent.com/55177318/82134191-c84f2d00-9827-11ea-8445-0cc7651fe0c7.png)
当然，也可以增加本地主题上传的功能类似下图：
![image](https://user-images.githubusercontent.com/55177318/82134183-b4a3c680-9827-11ea-9752-7332d90677b1.png)
另一方面，感觉`solo`的插件功能没有被发掘，如有可能后续可以增加一个插件中心实现插件的统一管理，对于非核心功能可以尝试以插件形式进行发布及更新。

**Comment by 88250** [comment]
感谢反馈，但我觉得没有这个必要，因为 Solo 主要用户是程序员，以程序员的方式来解决更好一些：

1. 作为皮肤作者，维护皮肤 GitHub 仓库
2. 作为皮肤用户，挂载命令参数不用动，需要做的是克隆仓库到本地 skins 下即可

我觉得对于作者和用户都是方便高效的。

插件方面有待挖掘，等待适合的应用场景出现。

**Comment by 88250** [comment]
先关闭了，如果以后有更进一步的想法欢迎随时反馈，谢谢。
