### ISSUE TITLE
新增 Markdown zip 导入方式

### ISSUE THREAD

**Issue by 88250** [88250/solo#128]
启动时读取目录 markdowns 的导入方式有点麻烦，特别是 Docker 部署时还需要挂载卷，很多用户操作不来，需要优化 😂 

工具 - 其他 - 数据导入中新增上传 Markdown zip 包导入方式，原目录启动导入方式依然保留。

**Comment by biehaiyang** [comment]
我刚刚更新完毕，没有找到。功能还没更新到docker吗

**Comment by 88250** [comment]
@biehaiyang 正在实现中，等该 issue close 了就说明实现完了 😄
