### ISSUE TITLE
文章支持点赞、感谢、收藏等主要交互功能

### ISSUE THREAD

**Issue by 88250** [88250/solo#131]
https://hacpai.com/article/1438049659432/comment/1590385916783?r=88250

可考虑在 [uvstat](https://github.com/Vanessa219/uvstat) 上实现。

**Comment by biehaiyang** [comment]
you are good 

I see some people with ak47,they biu biu biu and they boom boom boom.people say a a a and die.You should call a car which vivo vivo vivo ~

**Comment by 88250** [comment]
暂时不折腾了，以后慢慢想。
