### ISSUE TITLE
请问能不能关闭看板娘和一言功能？

### ISSUE THREAD

**Issue by xflcx1991** [88250/solo#136]
### 你在什么场景下需要该功能？
任何时候，是否有开关可以控制这两个功能
请尽量清晰精准地描述你碰到的问题。
* 看板娘太萌了，不太适合博客的风格。
* 一言太疯狂了，浏览器开发者工具看到的网络请求一刻不停的在请求一言。手机端岂不消耗流量？
### 描述可能的解决方案
分别为两个功能提供开关，以便 solo 博主自行决定要不要这两个功能。

**Comment by 88250** [comment]
工具 - 插件管理 - 看板娘

**Comment by 88250** [comment]
我关闭了，如果还有问题欢迎跟帖，谢谢。
