### ISSUE TITLE
后台认证登录的时候报404

### ISSUE THREAD

**Issue by yuanjifeng** [88250/solo#14]
输入后台地址https://www.simulate.net.cn/solo/start跳转到登录界面后点击“登录 GitHub 账号后即可开始使用”然后就报错了，URL是这个：https://www.simulate.net.cn/solo/oauth/github/redirect?referer=https://www.simulate.net.cn/solo__1
之前是好好的，最近才出现的，你们的是这样吗？

**Comment by 88250** [comment]
请看[这里](https://hacpai.com/article/1576294445994)。
