### ISSUE TITLE
文章链接是IP

### ISSUE THREAD

**Issue by loogn** [88250/solo#140]
### 描述问题

docker run中提供了--server_host为域名，但是文章列表、登录地址等等，都变成了IP:Port的形式

### 期待的结果

期望链接还是能以域名的形式展现

### 截屏或录像

![image](https://user-images.githubusercontent.com/967886/84243004-2ecc2000-ab34-11ea-91e1-7d3763789ec6.png)

**Comment by adlered** [comment]
到博客的后台设置-偏好设定里设置下域名

**Comment by 88250** [comment]
应该是启动参数没加对，你看下启动后的日志，里面会打参数。

**Comment by loogn** [comment]
我的docker是这样启动的
`sudo docker run --detach --name solo --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="***" \
    --env JDBC_PASSWORD="**********" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    b3log/solo --listen_port=8080 --server_scheme=http --server_host=www.loogn.net --server_port=`

日志里是这样，好像没什么有用的信息：
`[INFO ]-[2020-06-10 15:38:24]-[org.b3log.solo.Server:253]: Solo is booting [ver=4.1.0, os=Linux, isDocker=true, inJar=false, luteAvailable=false, pid=1, runtimeDatabase=MYSQL, runtimeMode=PRODUCTION, jdbc.username=solo, jdbc.URL=jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC]                                                                                                                                                         
[INFO ]-[2020-06-10 15:38:25]-[org.b3log.solo.util.Skins:70]: Loaded template from directory [/opt/solo/]                                                         
[INFO ]-[2020-06-10 15:38:25]-[org.b3log.solo.Server:300]: Solo is running                                                                                        
[INFO ]-[2020-06-10 15:38:40]-[org.b3log.solo.service.ExportService:344]: Backup all articles to HacPai....                                                       
[INFO ]-[2020-06-10 15:38:40]-[org.b3log.solo.service.ExportService:400]: Backup all articles to HacPai completed: {"sc":0}                                       
[INFO ]-[2020-06-10 15:38:57]-[org.b3log.solo.processor.OAuthProcessor:205]: Logged in [name=loogn, remoteAddr=123.149.238.155] with oauth                        
[INFO ]-[2020-06-10 15:53:35]-[org.b3log.solo.processor.OAuthProcessor:205]: Logged in [name=loogn, remoteAddr=123.149.238.155] with oauth  `

**Comment by 88250** [comment]
那应该是 NGINX 反代没有配置头，参考一下[这里](https://hacpai.com/article/1492881378588#NGINX-%E5%8F%8D%E4%BB%A3)

**Comment by loogn** [comment]
ok，应该是反向代理的问题，我用的ocelot，不支持header头，惨了！！！
