### ISSUE TITLE
增加取消选中文本朗读功能开关

### ISSUE THREAD

**Issue by xflcx1991** [88250/solo#141]
### 你在什么场景下需要该功能？
任何场景下

### 请尽量清晰精准地描述你碰到的问题。
选中文字出现播放按钮，点击就朗读文本。英文正常，中文不正常。
### 描述可能的解决方案
能否取消给个取消这个功能的开关？

**Comment by 88250** [comment]
> 选中文字出现播放按钮，点击就朗读文本。英文正常，中文不正常。

不正常的表现是什么样子的？另外请给一下浏览器版本和相关信息。

> 能否取消给个取消这个功能的开关？

稍后加入个开关来控制。

**Comment by xflcx1991** [comment]
> > 选中文字出现播放按钮，点击就朗读文本。英文正常，中文不正常。
> 
> 不正常的表现是什么样子的？另外请给一下浏览器版本和相关信息。
> 
> > 能否取消给个取消这个功能的开关？
> 
> 稍后加入个开关来控制。

选中1个汉字，念一声“letter”，选中2个汉字，念两声“letter”，以此类推。
Ubuntu 16.04 Firefox 77.0.1
另外，用Chrome 83 无法读出声音。

**Comment by 88250** [comment]
Firefox 可能支持不好，估计是 Ubuntu 没支持，Mac  和 Windows 上倒是没问题。
