### ISSUE TITLE
友情链接偶尔会404-好像是因为换皮肤后

### ISSUE THREAD

**Issue by wpengsen** [88250/solo#143]
我昨天换了个皮肤，忘记是换的移动皮肤还是pc皮肤了，然后点击友情链接404了

**Comment by 88250** [comment]
请继续观察以帮助我们确定问题，谢谢。

**Comment by wpengsen** [comment]
导航栏有几个固定的链接在后台设置中好像不能编辑也去不掉呀（标签墙、rss、友情链接。。。。。）

**Comment by 88250** [comment]
友情链接应该不是模板里写死的，其他几个是写死的功能入口。

**Comment by 88250** [comment]
暂时没有问题的话我关闭了，如果后续发现问题请继续跟帖，谢谢。
