### ISSUE TITLE
可不可以加一个图片上传到kodcloud的入口，读取的时候也从这里读取

### ISSUE THREAD

**Issue by wpengsen** [88250/solo#144]
### 我自己弄了一个自己的网盘（可道云）----可道云免费，而且现在还木有限速，坚果云好像还限制流量啥的

有的时候很想用以前自己上传过的，或者在迁移网站到其他域名什么的时候能直接无缝衔接

**Comment by 88250** [comment]
#145 中已做回复，谢谢。
