### ISSUE TITLE
文章配图木有办法用自己的

### ISSUE THREAD

**Issue by wpengsen** [88250/solo#145]
### 期待的结果

可以更换配图，在后台能有菜单查看自己上传过的图片

### 其他信息

我去看了下之前好像有人提出类似的问题，可能你们后来正在解决或者有其它考虑，我只在这里再提一遍，请见谅........

**Comment by 88250** [comment]
文章配图默认用的是正文中第一张图片，博客端可以使用非社区图床，但是用了非社区图床以后文章就不能推送到社区了。

https://github.com/88250/solo/issues/144 一并回答，建议使用社区图床，后期如果考虑迁移的话我们会支持全数据（包括图床文件）的导出，方便用户迁移其他平台，谢谢。

**Comment by wpengsen** [comment]
图床这块我不是太了解，上传的图片我看着您这都是存储的全路径地址，如果是上传到其他地方到时候拿到的也是全路径地址直接放进去是不是也能起到跟现在一样的效果（ps我看着您这里边可能还设计着一些其他图片功能，可能会跟这个冲突，这可能就是你们一般不建议其他上传的原因吧）

**Comment by 88250** [comment]
可以用自建图床然后全路径引用，博客端可以展现，试下看看就知道了。

**Comment by 88250** [comment]
我先关闭了，谢谢反馈。
