### ISSUE TITLE
自动生成的文章链接重复问题优化

### ISSUE THREAD

**Issue by xflcx1991** [88250/solo#147]
### 你在什么场景下需要该功能？

在发布新文章或导入新文章时。

目前我看到文章生成规则是日期+时间毫秒（是oid，但是oid的值就是毫秒数），这似乎不太合理。我在导入大量文档时就遇到了重复链接的报错，直到翻源码才发现原来是这个规则。
![NFMacT.png](https://s1.ax1x.com/2020/06/16/NFMacT.png)

可以理解作者的意思是不可能同时写多篇文章。
但是
* 多人写文章恰好时间相同
* 导入过去的markdown文档，有些文档的hexo头写的时间还就一样，还不是一个两个，手动改太费劲
遇到上述情况将发生导入失败，日志能看到`org.b3log.latke.service.ServiceException: 链接重复！`的错误。

### 描述可能的解决方案

可以参考 WordPress 的文章链接生成方案
![WordPress永久链接设置](https://pic4.zhimg.com/bf097441b860f0fedb7225001cdf6cbc_r.jpg)

### 描述你认为的候选方案

暂无

### 其他信息

暂无

**Comment by 88250** [comment]
这一块之前有过考虑，但是因为规则模式的使用其实并不常用，更推荐的做法是写文章是自定义链接。

导入的问题稍后加入延时进行解决，谢谢反馈！
