### ISSUE TITLE
社区设置英文后无法切换回中文

### ISSUE THREAD

**Issue by dxyhymn** [88250/solo#148]
![image](https://user-images.githubusercontent.com/45393154/84878973-2f792f00-b0bd-11ea-8d07-0a5962108487.png)
社区设置为英文后无法切换回中文

**Comment by 88250** [comment]
提交以后手动刷新界面能切换正常么？

**Comment by dxyhymn** [comment]
不行呀，试了很多次，退出重新登陆也不行。

**Comment by 88250** [comment]
谢谢反馈，稍后确认并修复。
