### ISSUE TITLE
推送到社区的文章无法评论

### ISSUE THREAD

**Issue by dxyhymn** [88250/solo#149]
![image](https://user-images.githubusercontent.com/45393154/84879338-a9a9b380-b0bd-11ea-9459-e8445c4e1241.png)

推送到社区的文章无法评论，是我设置有问题吗？

**Comment by 88250** [comment]
请帮忙确认一下 Chrome 浏览器能不能重现问题，谢谢。

**Comment by dxyhymn** [comment]
就是chrome 呀

**Comment by dxyhymn** [comment]
![image](https://user-images.githubusercontent.com/45393154/84880026-98ad7200-b0be-11ea-8aec-0f7bb4f985d6.png)

**Comment by 88250** [comment]
谢谢反馈，稍后确认并修复。

**Comment by Vanessa219** [comment]
http://dxyhymn.com/articles/2020/05/25/1590400905461.html

我试了一下可以的。Chrome 的版本号是？

**Comment by dxyhymn** [comment]
![image](https://user-images.githubusercontent.com/45393154/84882011-373ad280-b0c1-11ea-97d4-5f29d94e6c2a.png)

**Comment by 88250** [comment]
我刚刚也试了一下 Windows 上和你 Chrome 版本一样，没问题可以评论的……

**Comment by dxyhymn** [comment]
为啥我的还是不行，换Firefox也不行

**Comment by dxyhymn** [comment]
![image](https://user-images.githubusercontent.com/45393154/84882928-86cdce00-b0c2-11ea-9602-194cafc3a398.png)
而且在 https://hacpai.com/ 这个域名下都不能点评论按钮，点评论右下角的按钮报错

**Comment by 88250** [comment]
看之前的报错信息是因为跨域问题，但是所需 CROS 跨域标头还有预取请求这些细节都处理过的，理论上应该没问题。

目前看来有可能是因为设置英文的那个问题导致，稍后我们先解决英文设置问题，然后再回过头来看这个，谢谢。

**Comment by Vanessa219** [comment]
英文设置在社区确实有问题，但是不影响 solo 的评论。我刚才设置为英文再在你的博客上评论也是可以的

**Comment by 88250** [comment]
@dxyhymn 浏览器有单独设置过跨域相关选项么？或者有没有插件控制这个？

**Comment by dxyhymn** [comment]
没有啊

**Comment by Vanessa219** [comment]
麻烦再试一下社区和博客

**Comment by dxyhymn** [comment]
社区设置中文的好了，评论还是不行，还是跨域问题

**Comment by 88250** [comment]
这就很尴尬了……我们这里重现不了，该 issue 继续观察，希望还有其他人帮忙反馈。

**Comment by dxyhymn** [comment]
找到原因了，没有绑定手机号就评论不了，绑定手机号就好了。

**Comment by 88250** [comment]
谢谢，稍后我们改进一下报错提示。
