### ISSUE TITLE
【待优化】每个匹配路由的处理都会重复加载一遍skin目录

### ISSUE THREAD

**Issue by jetablezhu** [88250/solo#15]
非bug，不过每次handle一个请求，皮肤解析都会遍历一次皮肤目录，完全没必要，皮肤在应用启动时加载一次就可以了，这个Set完全可以缓存起来用。
![image](https://user-images.githubusercontent.com/9970753/71157966-f3841f00-227d-11ea-8c1b-62336cfe34cf.png)
![image](https://user-images.githubusercontent.com/9970753/71157980-fa129680-227d-11ea-9732-f8ff88da7adb.png)

**Comment by 88250** [comment]
感谢反馈，不过这里没有性能问题，所以暂时不改了 🙏
