### ISSUE TITLE
修改了后台管理中的一个js，如何编译生效呢？

### ISSUE THREAD

**Issue by yuanjifeng** [88250/solo#152]
修改了solo\src\main\resources\js\admin\pageList.js，希望在页面生效，请问如何操作？或者有对应的教程链接发我也行，从事后端多年对前端还不甚了解，多谢赐教。

**Comment by Vanessa219** [comment]
https://hacpai.com/article/1493814851007#%E5%BC%80%E5%8F%91%E6%AD%A5%E9%AA%A4
```
npm run build
```

**Comment by yuanjifeng** [comment]
根据文档说明安装了node环境，在solo项目根目录运行npm install后，再运行npm run build，问题已解决，非常感谢。

**Comment by Vanessa219** [comment]
😊
