### ISSUE TITLE
静态博客页脚的相关阅读、随机阅读不显示文章列表

### ISSUE THREAD

**Issue by GlacierBo** [88250/solo#155]
如题：静态博客页脚的相关阅读、随机阅读不显示文章列表
https://blog.fpdan.cn/articles/2020/06/25/1593042817922.html

示例博客页脚也存在相同问题，应该不是我配置的问题
https://88250.github.io/articles/2020/02/09/1581219038316.html

![image-60c46f22](https://user-images.githubusercontent.com/23645910/85737502-04808200-b732-11ea-9825-abd53b3bf36a.png)

**Comment by 88250** [comment]
谢谢反馈，目前在生成静态站点时故意去掉了这两块，因为没有响应可以伺服的后端接口。

**Comment by 88250** [comment]
目前的解决方案是生成时打开相关阅读和随机阅读，所以随机这块就不会一刷一变了。
