### ISSUE TITLE
自动转存图片

### ISSUE THREAD

**Issue by mmzsblog** [88250/solo#158]
比如我从博客园复制的我的文章，文章使用的 md 格式，文中的图片地址是博客园的；如果我直接复制整篇文章到 solo 会出现图片访问不了；

想问下 D 大，下个版本能不能考虑加个功能：复制过来的文章中的图片自动转存成 b3blog 存储地址，这样当图片很多时就不用一张一张上传了。

**Comment by 88250** [comment]
这个特性已在 v4.3.0 中计划实现，请关注该 issue https://github.com/88250/solo/issues/114
