### ISSUE TITLE
在首页新增最多访问与最多评论

### ISSUE THREAD

**Issue by jianzh5** [88250/solo#162]
### 你在什么场景下需要该功能？

想在首页上可以加上最多访问  和 最多评论的 文章列表

### 描述可能的解决方案

如果有人不喜欢这个功能，可以在后台添加开关控制是否前端加载

**Comment by 88250** [comment]
该功能会在[移除本地评论系统](https://github.com/88250/solo/issues/161)后考虑，谢谢反馈。

**Comment by 88250** [comment]
v4.3.1 后默认的评论系统是集成 Gitalk 进行实现（参考 [Solo 集成 Gitalk 评论系统](https://hacpai.com/article/1594988019287)），方便没有黑客派的访客和博主进行交互。浏览统计系统也是独立于 Solo 外的 UVStat 组件实现的，所以现在要做这两者的统计是比较困难的。

以后也许还会有大的调整，到时候再看吧，谢谢。
