### ISSUE TITLE
编辑器编辑模式切换造成表格渲染问题

### ISSUE THREAD

**Issue by ghostsf** [88250/solo#166]
所见所得 <-> 分屏预览

![image](https://user-images.githubusercontent.com/9978816/87109137-701c3080-c296-11ea-95e0-9979f272d60f.png)

![image](https://user-images.githubusercontent.com/9978816/87109117-65fa3200-c296-11ea-8bd9-0051579fea2d.png)

表格markdown内容变了，然后渲染出错了

**Comment by ghostsf** [comment]
![Kapture 2020-07-10 at 10 14 12](https://user-images.githubusercontent.com/9978816/87109197-9a6dee00-c296-11ea-98bf-d108443c4545.gif)

**Comment by 88250** [comment]
收到，这是因为目前版本的编辑器走的是后端渲染，后端需要开启 Lute HTTP 才能渲染表格等 GFM 语法。

下周将升级一次编辑器，分屏预览模式走浏览器端渲染，但是发布文章后最终前台的展示还是依赖 Lute HTTP 渲染。

Issue 我关了，谢谢反馈。

**Comment by TerickJojo** [comment]
> 收到，这是因为目前版本的编辑器走的是后端渲染，后端需要开启 Lute HTTP 才能渲染表格等 GFM 语法。
> 
> 下周将升级一次编辑器，分屏预览模式走浏览器端渲染，但是发布文章后最终前台的展示还是依赖 Lute HTTP 渲染。
> 
> Issue 我关了，谢谢反馈。

最新版本问题仍然存在

**Comment by 88250** [comment]
@TerickJojo 开启 Lute HTTP 了吗？

**Comment by TerickJojo** [comment]
> @TerickJojo 开启 Lute HTTP 了吗？

问题解决了，没注意lute还要单独拉取，哈哈

请问lute可以聚合进solo嘛？

**Comment by 88250** [comment]
@TerickJojo Lute 是 Golang 写的
