### ISSUE TITLE
集成 Gitalk 评论系统

### ISSUE THREAD

**Issue by 88250** [88250/solo#167]
v4.3.1 中已经完成开发，具体使用方式请看 [Solo 集成 Gitalk 评论系统](https://hacpai.com/article/1594988019287)。

**Comment by iTanken** [comment]
万事俱备 😀

![image](https://user-images.githubusercontent.com/23544702/87780109-94f94080-c860-11ea-8259-2c1d127d7687.png)

**Comment by jianfei96** [comment]
还是死循环

docker部署->登录链滴社区账号后即可开始使用->没有账号->注册账号->没有中国手机号码->无法注册->无法进入后台
不登录账号->没这个选项
Solo 集成 Gitalk 评论系统->在 Solo 后台的偏好设定 - 信息配置中配置页头和页脚->不登录账号无法进入后台

完全死局
