### ISSUE TITLE
solo的标签添加方式细节优化建议

### ISSUE THREAD

**Issue by vcjmhg** [88250/solo#173]
### 你在什么场景下需要该功能？

在进行博客写作的过程中难免需要添加中文标签，但在solo的标签添加框中必须要通过英文逗号进行分割。在添加多个标签的时候需要频繁的进行输入法更换，非常影响使用体验。
比如下图，我在添加完`机器学习`标签之后，希望继续添加`深度学习`这一标签的时候必须要切换到英文输入法输入逗号进行分割之后才能进行添加。
![结果](https://user-images.githubusercontent.com/55177318/88795664-ff9c6b80-d1d2-11ea-8aee-ece627dfccfa.gif)

### 描述可能的解决方案

关于标签添加过程，可以做出如下优化，首先感觉没有必要明显的用分隔符来进行分割，标签输入框中每个标签作为独立主体，在按回车确认只有可以继续输入下一个标签，如果输入的标签为新标签可以在简易列表中显示“添加新标签XXX”，点击回车之后即可添加。
整个过程类似于下图：
![结果](https://user-images.githubusercontent.com/55177318/88796429-31620200-d1d4-11ea-8751-4476fcac689b.gif)

### 其他信息

当然也可能solo的标签输入方式有更加方便输入方式，如果有的话，希望能够告知。谢谢！

**Comment by 88250** [comment]
感谢反馈，但目前暂时没有时间实现，见谅。
