### ISSUE TITLE
solo社区绑定手机失败，无法发布内容，无法私信，我只能来这里反馈了

### ISSUE THREAD

**Issue by KangKang-Wang** [88250/solo#176]
### 描述问题

![image](https://user-images.githubusercontent.com/32666425/90262920-857e0f00-de81-11ea-8a26-3b3232f76034.png)
一直都无法绑定手机号，我试了很久了

### 期待的结果

解决一下这个问题呗~

**Comment by 88250** [comment]
图形验证码确定输入正确么？

**Comment by KangKang-Wang** [comment]
> 图形验证码确定输入正确么？

正确的，老大，我试过几百次了

**Comment by KangKang-Wang** [comment]
> > 图形验证码确定输入正确么？
> 
> 正确的，老大，我试过几百次了

诶，现在再试好了耶，你有操作什么么

**Comment by 88250** [comment]
没有。

**Comment by KangKang-Wang** [comment]
> 没有。

emmmmmmmmm.....

**Comment by 88250** [comment]
能用就行。

**Comment by adlered** [comment]
卧槽，我以为我手机被短信轰炸了
