### ISSUE TITLE
取不到userinfo  本地社区solo登入不了

### ISSUE THREAD

**Issue by xiaobing395845388** [88250/solo#181]
本地部署的solo没做任何升级，登入时候目前出现问题，后台日志提示 Can't get user info with token [ZnrWjR7xeYZxL99W]
调试到代码
```
final HttpResponse res = HttpRequest.post("https://hacpai.com/user/ak").
                    form("access_token", accessToken).trustAllCerts(true).
                    connectionTimeout(3000).timeout(7000).header("User-Agent", Solos.USER_AGENT).send();
```
响应301，取不到userinfo了
### 描述问题

请尽量清晰精准地描述你碰到的问题。

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
如果用 Docker 镜像部署的话请升级镜像，如果是发布包部署请等我们发布 v4.3.1，谢谢。

**Comment by 88250** [comment]
大概几小时后就会发布 v4.3.1。

**Comment by xiaobing395845388** [comment]
刚才下载的最新的镜像 b3log/solo:latest  起来之后 里面的版本还是4.3.0呀

**Comment by 88250** [comment]
版本号还没变更，但是代码已经是最新的了。
