### ISSUE TITLE
编辑器在预览状态下发布文章会丢失代码块

### ISSUE THREAD

**Issue by 88250** [88250/solo#182]
重现方式：在最新的solo博客系统后台编辑一篇有代码块的文章，通过vditor预览，然后在不关闭预览的情况下直接提交发布，再次打开编辑代码就没了：

![Untitled](https://user-images.githubusercontent.com/6762068/92435527-2fc52a00-f1d5-11ea-9619-a571d7521515.gif)

_Originally posted by @thisdaydayde in https://github.com/Vanessa219/vditor/issues/746#issuecomment-688622880_

**Comment by Vanessa219** [comment]
610ac691993ba1355d360bb25559ac723e530b49
