### ISSUE TITLE
说一下移除本地评论系统这个做法的缺陷

### ISSUE THREAD

**Issue by jianfei96** [88250/solo#184]
移除本地评论系统导致社区账号成为必须，但社区账号有两个问题：必须注册，无法注册
例如我看到https://ld246.com/article/1594478511380
评论都发不了只能发issue

我捋一捋，社区必须注册对吧，然后社区好像是要求必须提供中国大陆的手机号码。
这样导致的问题有两个，海外无法注册，隐私安全问题
solo还支持多语言和国际化，这个支持法可太鬼才了。

详细说下隐私安全问题：
   1. 真的有人为了发个评论特意注册账户还要提供手机号码吗？
   2. 很多独立博客是重视隐私和意见表达的，搞个备案网站强制要求提供手机号码真的没问题吗？

单纯吐槽一下提提意见，评论系统搞成这样博客下面反对的意见想发都发不出来。其他没什么好说的，直接close issue也没关系/

**Comment by 88250** [comment]
请看 v4.3.1 做出的改进：[集成 Gitalk 评论系统](https://github.com/88250/solo/issues/167)。
