### ISSUE TITLE
img.hacpai.com 图床所有图片都 403

### ISSUE THREAD

**Issue by panjf2000** [88250/solo#185]
**请先看[《提问的智慧》](https://ld246.com/article/1536377163156)**，并尝试到[链滴](https://ld246.com)搜寻资料解决问题。

----

### 描述问题

我的 img.hacpai.com 图床所有图片都 403 了，是什么问题？https://img.hacpai.com/file/2019/08/book-4e46a954.jpg

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by panjf2000** [comment]
好像又偶尔会恢复，但是基本都是403。。。。

**Comment by 88250** [comment]
目前社区图床禁止外链，只能在博客端和社区端使用。

**Comment by panjf2000** [comment]
我是在博客端使用的啊，而且我看其他人的图片没问题啊：https://b3logfile.com/file/2020/08/image-83e20393.png?imageView2/2/w/1280/format/jpg/interlace/1/q/100

**Comment by panjf2000** [comment]
我的全部都不行了，https://b3logfile.com/file/2020/06/docker-1a1a11cd.png?imageView2/2/w/1280/format/jpg/interlace/1/q/100，不过我刚把博客搬到境外的服务器上而且换了域名，和这个有关系吗？

**Comment by 88250** [comment]
域名下 `/blog/info` 这个路径要能在国内访问通。
