### ISSUE TITLE
使用内置皮肤yilia报500错误

### ISSUE THREAD

**Issue by FunctFan** [88250/solo#187]
最近升级了solo最新版本，使用的皮肤一直是内置皮肤，但这次升级完成之后点击分类标签查看文章时，直接报500内部错误，而使用next主题时显示正常，麻烦解决一下。
![image](https://user-images.githubusercontent.com/45038279/94504782-252e0b80-023c-11eb-9d11-e1905cc5da50.png)

**Comment by 88250** [comment]
你好，我这里正常的。先关闭了，如果有进一步细节请继续反馈，谢谢。
