### ISSUE TITLE
请问我之前写的博客，为什么文章中的图片无法显示？

### ISSUE THREAD

**Issue by njqaaa** [88250/solo#189]
使用的是h2数据库
1、复制原有h2数据库文件至新目录
2、使用docker run 挂载新目录下的数据库文件
问题如下
1、博客中的图片无法显示
2、首次登陆，会跳转异常（github登陆），显示未登录成功，重复尝试，则可以正常登录
3、登出页面异常。 点击登出，浏览器依然显示登录状态，实际已登出

有一定概率h2数据库与代码兼容性问题。
请大神看下什么情况。
核心问题是 博客中的图片无法显示，其他2个问题不大，

![image](https://user-images.githubusercontent.com/5145656/95676876-fe84b300-0bf3-11eb-8d4c-ad6e383a049a.png)

![image](https://user-images.githubusercontent.com/5145656/95676865-e3b23e80-0bf3-11eb-9904-4081e5b0aa78.png)
![image](https://user-images.githubusercontent.com/5145656/95676943-a7331280-0bf4-11eb-82b5-62332023fe5e.png)

**Comment by 88250** [comment]
* 先登录社区，再登录博客端
* 图床的问题后面继续观察

我关闭了，有问题请跟帖。
