### ISSUE TITLE
HTML 静态站点生成

### ISSUE THREAD

**Issue by 88250** [88250/solo#19]
博客前台所有页面均可生成 HTML 静态页，导出在一个目录中以实现静态站点托管。

皮肤模板主要修改点：

* [x] 分页链接中的 `?p=` 改为使用变量 `${pagingSep}`
* [x] 根据变量 `${staticSite}` 判断是否展示`开始使用`、`Search` 的入口
* [x] 管理后台增加功能入口 UI，需要用户输入静态站点域名

**Comment by hmfcookie** [comment]
mvn site 
then :
    ClassNotFoundException: org.apache.maven.doxia.siterenderer.DocumentContent   
why?

![image](https://user-images.githubusercontent.com/33307338/77132364-1bac3580-6a9a-11ea-9e31-cf1b2f581d83.png)

**Comment by 88250** [comment]
> ClassNotFoundException: org.apache.maven.doxia.siterenderer.DocumentContent why?

静态站点生成不用 mvn 命令，使用方式请看[这里](https://hacpai.com/article/1579053576274)。

**Comment by hmfcookie** [comment]
> > ClassNotFoundException: org.apache.maven.doxia.siterenderer.DocumentContent why?
> 
> 静态站点生成不用 mvn 命令，使用方式请看[这里](https://hacpai.com/article/1579053576274)。

ok.Thanks.
