### ISSUE TITLE
最新版solo docker部署域名设置无效

### ISSUE THREAD

**Issue by BB-fat** [88250/solo#192]
您好，我大概两年前开始使用solo，非常喜欢这个项目，昨天发现不能用GitHub账号登陆了，更换社区登录之后显示我没有权限进入后台，我看到论坛帖子说要更新到最新版本，正好我也好久没有更新了，所以就拉了一个最新版的镜像，启动之后访问网站发现浏览器请求不到资源。

<img width="636" alt="image" src="https://user-images.githubusercontent.com/45072480/101239237-fbec9880-3720-11eb-9970-695134f271c6.png">

我使用的命令如下：
```
docker run --detach --name solo --network=host --env RUNTIME_DB="MYSQL" --env JDBC_USERNAME="<用户名>" --env JDBC_PASSWORD="<密码>" --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true" b3log/solo --listen_port=8080 --server_scheme=https --server_host=www.fatech.online
```
使用nginx反向代理，一切正常，折腾好久没有解决，在社区里也没有看到相同问题，朋友使用相同版本也正常，请帮我看一下，谢谢。

**Comment by 88250** [comment]
> 使用nginx反向代理，一切正常

那就是用 NGINX 反代吧……

**Comment by BB-fat** [comment]
抱歉，我的描述有误，我的意思是网站是通过Nginx反响代理的，可以正常访问到各个页面，但是页面上的资源路径和文章链接都是127.0.0.1:8080/....，并没有替换成server_host的值，导致那些资源请求不到。

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45072480/101239654-50454780-3724-11eb-9b2f-df15a4e5c251.png">

**Comment by 88250** [comment]
哦，看下用户指南，里面有说明需要设置反代标头。

**Comment by BB-fat** [comment]
可以了，感谢！
