### ISSUE TITLE
点击分类出现500

### ISSUE THREAD

**Issue by wenyl** [88250/solo#196]
![image](https://user-images.githubusercontent.com/24486381/109099824-b4453e00-775e-11eb-8779-cb5b73cd62e5.png)
访问地址
http://www.wenyoulong.com/category/code-life

**Comment by 88250** [comment]
请帖下日志。

**Comment by wenyl** [comment]
[ERROR]-[2021-02-25 11:44:23]-[org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer:104]: Renders template [category-articles.ftl] failed [Request [
&nbsp; &nbsp; method=GET,
&nbsp; &nbsp; URI=/category/code-life,
&nbsp; &nbsp; contentType=null,
&nbsp; &nbsp; remoteAddr=39.129.17.155,
&nbsp; &nbsp; headers=[
&nbsp; &nbsp; &nbsp; &nbsp; Host=www.wenyoulong.com
&nbsp; &nbsp; &nbsp; &nbsp; Connection=keep-alive
&nbsp; &nbsp; &nbsp; &nbsp; Upgrade-Insecure-Requests=1
&nbsp; &nbsp; &nbsp; &nbsp; User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
&nbsp; &nbsp; &nbsp; &nbsp; Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
&nbsp; &nbsp; &nbsp; &nbsp; Accept-Encoding=gzip, deflate
&nbsp; &nbsp; &nbsp; &nbsp; Accept-Language=zh-CN,zh;q=0.9
&nbsp; &nbsp; &nbsp; &nbsp; Cookie=LATKE_SESSION_ID=aUzfp6ILhE6xSJkq; solo=1afd779183e1e71f2accd25f7edb5e82331660aa7adc571e143e0a8687465da56972361bc2f068815f67fa602d2f34668b3f31bc655f2b6274fda495e09989bb
&nbsp; &nbsp; &nbsp; &nbsp; content-length=0
&nbsp; &nbsp; ]
]]
freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
==&gt; category.categoryPublishedArticleCount&nbsp; [in template "skins/yilia/category-articles.ftl" at line 28, column 20]
----
Tip: It's the step after the last dot that caused this error, not those before it.
----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??&gt;when-present<#else&gt;when-missing</#if&gt;. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----
----
FTL stack trace ("~" means nesting-related):
&nbsp; &nbsp; &nbsp; &nbsp; - Failed at: ${category.categoryPublishedArticleCo...&nbsp; [in template "skins/yilia/category-articles.ftl" at line 28, column 18]
----
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.DollarVariable.accept(DollarVariable.java:63) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.Environment.visit(Environment.java:334) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.Environment.visit(Environment.java:340) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.core.Environment.process(Environment.java:313) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at freemarker.template.Template.process(Template.java:383) ~[freemarker-2.3.30.jar:2.3.30]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.genHTML(AbstractFreeMarkerRenderer.java:127) ~[latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.solo.processor.SkinRenderer.genHTML(SkinRenderer.java:81) ~[solo/:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer.render(AbstractFreeMarkerRenderer.java:98) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.Dispatcher.renderResponse(Dispatcher.java:120) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.Dispatcher.handle(Dispatcher.java:92) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:78) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.ServerHandler.channelRead0(ServerHandler.java:34) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.WebSocketHandler.handleHttpRequest(WebSocketHandler.java:90) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at org.b3log.latke.http.WebSocketHandler.channelRead0(WebSocketHandler.java:47) [latke-core-3.4.10.jar:?]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.49.Final.jar:4.1.49.Final]
&nbsp; &nbsp; &nbsp; &nbsp; at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 中午11:45
收件人: "88250/solo"<solo@noreply.github.com&gt;; 
抄送: "Long"<3424675994@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [88250/solo] 点击分类出现500 (#196)





 
请帖下日志。

**Comment by 88250** [comment]
你好，可能是升级后主题不兼容了，请升级到对应版本的主题。

**Comment by wenyl** [comment]
更新到最新的docker镜像了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 中午11:58
收件人: "88250/solo"<solo@noreply.github.com&gt;; 
抄送: "Long"<3424675994@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [88250/solo] 点击分类出现500 (#196)





 
Closed #196.

**Comment by wenyl** [comment]
还是不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 中午11:58
收件人: "88250/solo"<solo@noreply.github.com&gt;; 
抄送: "Long"<3424675994@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [88250/solo] 点击分类出现500 (#196)





 
Closed #196.

**Comment by wenyl** [comment]
Casper这个皮肤也也有一个问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D"<notifications@github.com&gt;; 
发送时间: 2021年2月25日(星期四) 中午11:58
收件人: "88250/solo"<solo@noreply.github.com&gt;; 
抄送: "Long"<3424675994@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [88250/solo] 点击分类出现500 (#196)





 
Closed #196.

**Comment by 88250** [comment]
重建下分类试试。
