### ISSUE TITLE
支持Prometheus metrics

### ISSUE THREAD

**Issue by liangyuanpeng** [88250/solo#197]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

用于监控Solo程序metrics信息,例如CPU、内存、HTTP请求量等使用情况  

![image](https://user-images.githubusercontent.com/28711504/110574260-c203b600-8197-11eb-8e48-98bab283261f.png)

### 描述最优的解决方案 Describe the optimal solution

应用引入micrometer+prometheus的库, 可以很方便的开启metrics暴露  
```
PrometheusMeterRegistry prometheusRegistry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);

try {
    HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
    server.createContext("/prometheus", httpExchange -> {
        String response = prometheusRegistry.scrape(); (1)
        httpExchange.sendResponseHeaders(200, response.getBytes().length);
        try (OutputStream os = httpExchange.getResponseBody()) {
            os.write(response.getBytes());
        }
    });

    new Thread(server::start).start();
} catch (IOException e) {
    throw new RuntimeException(e);
}
```  

与SpringBoot的集成更是简单,但我不确定非SpringBoot应用是否只能开启一个新的HTTPServer.  

https://micrometer.io/docs/registry/prometheus

### 其他信息 Other information

  
如果我忽略了文档请提示我

**Comment by liangyuanpeng** [comment]
补充一点：Prometheus metrics数据格式目前已经是CNCF项目OpenMetrics的标准，因此 支持prometheus metrics暴露还是非常有必要的。

**Comment by 88250** [comment]
我们不打算加入，如果必须的话请 Fork 自行修改，谢谢。
