### ISSUE TITLE
Solo 博客目录中的一级标题和二级标题之间没有缩进

### ISSUE THREAD

**Issue by wangzk1900** [88250/solo#204]
### 描述问题

Solo 博客目录中的一级标题和二级标题之间没有缩进，尝试多个主题（皮肤），都有这个问题。

### 期待的结果

建议在生成的目录中的一级标题和二级标题之间添加缩进。

### 截图

<img width="918" alt="2021-05-10_104112" src="https://user-images.githubusercontent.com/50759612/117603280-43ba9480-b185-11eb-89dd-fdbf25ee2492.png">

<img width="659" alt="2021-05-10_114721" src="https://user-images.githubusercontent.com/50759612/117603409-8e3c1100-b185-11eb-8eb3-08722e52e397.png">

### 版本环境

使用的是最新的 solo docker 镜像，上午刚更新的。

**Comment by wangzk1900** [comment]
同样存在这个问题 



***@***.***
 
发件人： D
发送时间： 2021-05-11 22:54
收件人： 88250/solo
抄送： wangzk1900; Author
主题： Re: [88250/solo] Solo 博客目录中的一级标题和二级标题之间没有缩进 (#204)
请试下 Bubble 皮肤。

**Comment by 88250** [comment]
使用最新的 Lute HTTP 和 Solo 镜像试试，我这里没有问题哦。

**Comment by wangzk1900** [comment]
我用的是最新的镜像，两天前刚更新的。
下面的截图是您博客中的一篇文章，我把 class 分别修改为：h1,h2,h3,h4，对应的目录中，一级标题和二级标题同样是没有缩进的。





***@***.***
 
发件人： D
发送时间： 2021-05-12 09:19
收件人： 88250/solo
抄送： wangzk1900; Author
主题： Re: [88250/solo] Solo 博客目录中的一级标题和二级标题之间没有缩进 (#204)
使用最新的 Lute HTTP 和 Solo 镜像试试，我这里没有问题哦。

**Comment by 88250** [comment]
看下这篇 https://88250.b3log.org/articles/2020/04/23/1587637426085.html

**Comment by wangzk1900** [comment]
建议在 `solo/src/main/resources/scss/_toc.scss` 文件中增加二级标题的缩进样式。应该能解决这个问题。

**Comment by 88250** [comment]
欢迎 pr。

**Comment by wangzk1900** [comment]
已提交pr
