### ISSUE TITLE
数学公式无法正常渲染

### ISSUE THREAD

**Issue by zhaoyangkun** [88250/solo#208]
最新版 solo 博客无法正常渲染数学公式
![image](https://user-images.githubusercontent.com/29301950/119071012-9ca6ea00-ba1b-11eb-93a8-b20db253d478.png)

**Comment by 88250** [comment]
使用了 Lute HTTP 吗？

**Comment by zhaoyangkun** [comment]
> 使用了 Lute HTTP 吗？

使用了

**Comment by zhaoyangkun** [comment]
> 使用了 Lute HTTP 吗？

现在可以正常渲染公式了，刚才不知道怎么回事

**Comment by 88250** [comment]
好的，那先关闭了。

**Comment by zhaoyangkun** [comment]
> 好的，那先关闭了。

行
