### ISSUE TITLE
solo 启动参数无法正常挂载卷

### ISSUE THREAD

**Issue by KangKang-Wang** [88250/solo#209]
### 描述问题 Describe the problem

想把整个solo的目录映射到一个目录去，方便自己取用文件，但是在使用-v参数或者--v参数又或者-volume参数或者--volume参数去挂载都失败了。要么 unknown flag: --v，要么命令是执行了，可是容器退出了，查看docker logs solo打印的内容为：Error: Could not find or load main class org.b3log.solo.Server

命令如下：docker run  --detach --name solo -v /solo:/opt/solo --network=host\
  --env RUNTIME_DB="MYSQL" --env JDBC_USERNAME="root"\
  --env JDBC_PASSWORD="xxxx" \
  --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
  --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/solo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"  b3log/solo --listen_port=8080 --server_scheme=https 

![image](https://user-images.githubusercontent.com/32666425/119802348-0f7afe00-bf11-11eb-8665-6046600c0d6a.png)

### 版本环境 Version environment

* 版本 Version：最新版
* 操作系统 Operating system：centos
* 浏览器 Browser：none

**Comment by 88250** [comment]
挂载卷的话容器里面文件就被宿主机的覆盖了，所以找不到启动入口。
