### ISSUE TITLE
社区图床更换新域名

### ISSUE THREAD

**Issue by 88250** [88250/solo#21]
从 `img.hacpai.com` 更换为 `b3logfile.com`，新上传的文件将会使用新域名，老地址仅支持老文件访问。

**Comment by adlered** [comment]
D哥，大概多久会搞好新的图床嘞 :smile:

**Comment by 88250** [comment]
@AdlerED 新域名还在备案，估计还需要个把月。

**Comment by adlered** [comment]
好的~

**Comment by adlered** [comment]
图床地址更改以后，旧版本的 Solo 还可以正常使用编辑器上传图片吗？还是需要修改 `Images.COMMUNITY_FILE_URL` 的值为 `b3logfile.com` ？

**Comment by 88250** [comment]
老的域名还可以继续读取的，不用迁移数据。新域名启用还早，之前估计个把月太乐观了……

**Comment by adlered** [comment]
哈哈哈，好的。那上传还是会有影响的吧？

**Comment by 88250** [comment]
上传不用操心，届时我会更新社区服务的。

**Comment by 9526xu** [comment]
请问下目前社区图床是否已经开启防盗链？

**Comment by 88250** [comment]
> 请问下目前社区图床是否已经开启防盗链？

开启的，仅可以在 Solo、Pipe 博客端节点和社区端使用。
