### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by yfdoor** [88250/solo#216]
今天登陆后台的时候突然登陆不上了。
重新拉取镜像部署，仍然无法解决。一直报 ”401 Unauthorized!“

查看后台log 记录显示： Can't get user info with token
[WARN ]-[2021-08-08 12:31:57]-[org.b3log.solo.processor.OAuthProcessor:137]: Can't get user info with token [RRYaI7tCJKIJocLy]

请帮忙看下还有其他方法吗，谢谢

**Comment by 88250** [comment]
社区服务器目前没有遇到问题，多半是你的服务端调用社区接口失败了，请在服务端看下网络是否通。

我先关闭了，如果还有问题请继续跟帖，谢谢。
