### ISSUE TITLE
Can not login to my solo blog due to connection failed

### ISSUE THREAD

**Issue by wuhaifengdhu** [88250/solo#220]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/3108520/129603514-a017454b-be4c-48e4-af0d-441dbee2fa5c.png">

**Comment by 88250** [comment]
请看下日志。

**Comment by wuhaifengdhu** [comment]
> 请看下日志。

日志在哪里？我是通过docker部署的。

**Comment by 88250** [comment]
可通过 docker logs 查看。

**Comment by 88250** [comment]
似乎你已经解决 https://ld246.com/article/1629136214526

我关闭了，谢谢。

**Comment by wuhaifengdhu** [comment]
> 似乎你已经解决 https://ld246.com/article/1629136214526
> 
> 我关闭了，谢谢。

是的，解决了。
