### ISSUE TITLE
希望官方镜像支持Multi architecture Docker，以支持arm/arm64服务器无痛pull&run。

### ISSUE THREAD

**Issue by Curious-r** [88250/solo#222]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?

使用ARM架构服务器或身边的树莓派之类的设备搭建博客时，最方便的方法是使用官方镜像，但目前官方docker镜像仅支持amd64架构。
### 描述最优的解决方案 Describe the optimal solution

或许可以参考这篇文章的构建方法：
[https://blog.csdn.net/dev_csdn/article/details/79138424](url)
### 描述候选解决方案 Describe the candidate solution

候选方案：单独提供带有arm64 tag的镜像；
候选方案2：帮忙指个路，没找到实机安装教程，想自己build找不到= =

**Comment by 88250** [comment]
你好，感谢建议，但目前暂时没有时间研究，欢迎 PR。

安装教程见 README，谢谢。
