### ISSUE TITLE
Markdown 导入的问题，请求大佬指点

### ISSUE THREAD

**Issue by vbskycn** [88250/solo#226]
**老大，上一个提问你关了，你说要从md导入，能具体指点一下吗？**

>
> 从别的博客转过来的，其它非常不错，还有就是一个固定连接修改报错的问题求大佬看看
> 在baidu还有些流量过来，不改成一样的就都404了
>
> 目前后台只能这种格式的
> /51670.html
> /articles/2021/01/09/1610192449213.html
> 改成其它的都会报错
>
> 但我以前wp是这种的
> /articles/1610192449213.html
>
> 请大佬修复，或给个方案，谢谢

> ### [88250](https://github.com/88250)  commented

| 使用 Markdown 导入，不然可能没辙…… |

**是从wp转过来的，通过插件导出了所有的文章为md文件**

******md里面也有原来的固定链接地址，但是导入solo后就自动生成了新的******

**
**老大能否帮看看，是不是导出的md文件有问题。link字段不能导入，有什么办法吗？
下面是我原wp倒出的md数据,能否帮忙看看，非常感谢****

**[https://zbds.lanzoui.com/b0b2mpzbc]([https://zbds.lanzoui.com/b0b2mpzbc](https://github.com/88250/solo/issues/url))

**

**Comment by 88250** [comment]
这个应该没办法处理，抱歉了。

**Comment by vbskycn** [comment]
好的谢谢
