### ISSUE TITLE
使用 TLS v1.2

### ISSUE THREAD

**Issue by 88250** [88250/solo#230]

**Comment by chaigx** [comment]
请问4.4.0什么时候发？我这边也遇到jodd.http.HttpException: Received fatal alert: protocol_version; <--- javax.net.ssl.SSLException: Received fatal alert: protocol_version的问题了。导致管理端登录不进去了，目前solo的版本是4.3.1，jdk的版本是11
![image](https://user-images.githubusercontent.com/6782627/149779931-1be51dae-15bd-4dd3-b844-3c47f34c67ce.png)
![image](https://user-images.githubusercontent.com/6782627/149779982-ac8ee494-3aa2-4e08-9848-2664a991984b.png)

**Comment by 88250** [comment]
@chaigx Docker 镜像已经发布了，zip 包的话目前没有时间打包，麻烦拉源码自行编译。

**Comment by chaigx** [comment]
使用dev分支还是master？

**Comment by 88250** [comment]
master

**Comment by chaigx** [comment]
好的
