### ISSUE TITLE
管理端搜索文章的时候，搜索结果中包含了其他没有该关键词的文章

### ISSUE THREAD

**Issue by wenming5112** [88250/solo#239]
### 描述问题 Describe the problem

搜索结果与预期不符。比如搜索redis，搜索出了其他不含这个词的文章。

### 期待的结果 Expected result

搜索出所有含redis的文章。

### 截屏或录像 Screenshot or video

![image](https://user-images.githubusercontent.com/36882090/158980150-d75b218a-7df8-4f5c-8722-e67e47312e9f.png)

### 版本环境 Version environment

应该所有版本都存在这个问题，我看issue中不存在该问题。
* 版本 Version：
* 操作系统 Operating system：
* 浏览器 Browser：

**Comment by wenming5112** [comment]
# 首页的搜索通用存在上面的问题
![image](https://user-images.githubusercontent.com/36882090/158986174-83bede68-ac1a-4f3d-a3b3-fb84119e32b7.png)

![image](https://user-images.githubusercontent.com/36882090/158986299-af1eba06-2949-4b73-920e-85b4a27460dc.png)

**Comment by 88250** [comment]
应该是文章正文中包含了。

**Comment by wenming5112** [comment]
怎么可能，肯定是没有包含啊，我搜索redis，结果一篇写docker的文章也搜索出来了（里面不包含redis）

**Comment by wenming5112** [comment]
我的，文章中确实是有与文章主题无关的关键词，导致搜索匹配不准确。我觉得这里可以优化，优先匹配分类和标签，如果没有命中则根据全文检索的结果来获取记录。简单来说呢就是分类和标签获取的记录和全文检索的记录取交集。

**Comment by 88250** [comment]
欢迎 PR 贡献改进代码。
