### ISSUE TITLE
Window 本地搭建完运行，链滴社区登录后出现localhost 目前无法处理此请求，是什么情况

### ISSUE THREAD

**Issue by luommy** [88250/solo#241]
### 版本环境 Version environment

* 版本 Version：
* 操作系统 Operating system：
* 浏览器 Browser：

**Comment by 88250** [comment]
请看下日志输出。

**Comment by luommy** [comment]
日志输出：
[ERROR]-[2022-04-06 14:59:46]-[org.b3log.latke.http.renderer.AbstractFreeMarkerRenderer:87]: Not found template [error/400.ftl]
顺便问一下大佬B站怎么不更新.

**Comment by 88250** [comment]
使用的主题是？

B 站没时间更新。
