### ISSUE TITLE
无网时，还能管理博客吗？

### ISSUE THREAD

**Issue by lyne408** [88250/solo#242]
### 无网还能管理博客吗？

部署在局域网里的。
有时候停电或者其他原因导致没有网络。
但是之前写的 blog 存在错误，需要改正。
但是那个 admin-index.do 一直 401，进不去。

怎么解决呢？

**Comment by 88250** [comment]
不行，请看 FAQ。

**Comment by lyne408** [comment]
> 不行，请看 FAQ。

## Solo is WAN-dependent

When downloading MySQL Community Server, login is optional.
When downloading MongoDB Community Server, login once.
When downloading XShell Home User Edition, login once.
When running MySQL Server, MongoDB Server or XShell, it's WAN-independent.

When running Solo Blog System, it's WAN-dependent.

## Solo 401 Page Codes

https://github.com/88250/solo/blob/7b93aa41fba2c5176fb2128c366af90db466e8fc/src/main/java/org/b3log/solo/processor/OAuthProcessor.java

```java
  final JSONObject userInfo = Solos.getUserInfo(accessToken);
  if (null == userInfo) {
      LOGGER.log(Level.WARN, "Can't get user info with token [" + accessToken + "]");
      context.sendError(401);
      return;
  }
```

https://github.com/88250/solo/blob/7b93aa41fba2c5176fb2128c366af90db466e8fc/src/main/java/org/b3log/solo/processor/console/AdminConsole.java

```java
  final Response response = context.getResponse();
  if (!Solos.isAdminLoggedIn(context)) {
      context.sendError(401);
      return;
  }
```

https://github.com/88250/solo/blob/e8450245b4e2ae725c354685dae17594088d53f2/src/main/java/org/b3log/solo/processor/console/ConsoleAuthMidware.java

```java
  final JSONObject currentUser = Solos.getCurrentUser(context);
  if (null == currentUser) {
      context.sendError(401);
      context.abort();
      return;
  }
```

https://github.com/88250/solo/blob/e8450245b4e2ae725c354685dae17594088d53f2/src/main/java/org/b3log/solo/processor/console/ConsoleAdminAuthMidware.java

```java
  if (!Solos.isAdminLoggedIn(context)) {
      context.sendError(401);
      context.abort();
      return;
  }
```

# Solutions of Solo WAN-independent

- Inject admin user in Java back-end source codes

## VEditor 还是很不错的. Solo 依赖 WAN, 有时不可用, 即不稳定. 不稳定, 则不用. 如果无用的话, 一般 User 也不会捐赠.
