### ISSUE TITLE
文章发布编辑页面出不来

### ISSUE THREAD

**Issue by chaigx** [88250/solo#246]
发现文章编辑页面出不来了，如图：
![image](https://user-images.githubusercontent.com/6782627/168730736-83f53b61-abf4-42d0-972a-d702fc07ccb8.png)
看问题是
https://cdn.jsdelivr.net/npm/vditor@3.8.4/dist/index.min.js
https://cdn.jsdelivr.net/npm/vditor@3.8.4/dist/js/icons/ant.js
2个js文件访问异常

麻烦看下怎么处理？

**Comment by 88250** [comment]
应该是因为 jsDelivr CDN 访问受限了，编辑器似乎是固定使用该 CDN，暂时只能科学上网解决。

后续有空会改为传参，使用 `static_server_host` 启动参数配置编辑器。

**Comment by Boss-Rabbit** [comment]
我刚刚看了下,您这边代码修改为了传参,但是 docker 镜像还是四个月前的镜像,所以通过 docker 镜像方式部署的还是有这个问题

**Comment by 88250** [comment]
请关注 https://github.com/88250/solo/issues/247
