### ISSUE TITLE
编辑器 CDN 从 `cdn.jsdelivr.net` 切换到 `unpkg.com`

### ISSUE THREAD

**Issue by 88250** [88250/solo#247]

**Comment by Boss-Rabbit** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/99818658/169960026-10fe2496-2e3d-471a-a293-bc17b10cca74.png">
b3log/solo 这个镜像并没更新,您可以更新一下这个镜像么
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/99818658/169963660-7251bb69-12c9-4776-b681-0165e29ba06a.png">
右边的文件是我从容器里面拿出来的

**Comment by 88250** [comment]
@Jonny-Chi 等这个 issue 关闭以后会构建新镜像。

**Comment by Boss-Rabbit** [comment]
好的,好的 @88250

**Comment by Boss-Rabbit** [comment]
@88250 #247 镜像更新了么

**Comment by 88250** [comment]
已经更新 

![image](https://user-images.githubusercontent.com/873584/170606170-c024c2f0-c1d7-491e-aca0-d580a2643983.png)
