### ISSUE TITLE
关于所见即所得

### ISSUE THREAD

**Issue by AlgerFan** [88250/solo#25]
1. 能否实现当所见即所得和源码模式切换时，光标位置不变，目前切换会直接回到顶部
2. markdown能否支持反撤销，有时手误撤销，发现没有反撤销，就需要重新打一遍。
另外所见即所得模式真的舒服，居中写文章也很舒服，点个赞🤣🤣

**Comment by 88250** [comment]
收到，稍后改进模式切换时保留光标位置，感谢反馈！

redo/undo 是支持的，你看下工具栏上有。

**Comment by AlgerFan** [comment]
抱歉，没注意，但是不太符合习惯，一般情况都是Ctrl shift+C😂😂

**Comment by 88250** [comment]
issue 我先关闭了，你注意定时更新镜像就行。

**Comment by AlgerFan** [comment]
留步😁，PC端使用小窗（大概手机大小），再切换为正常PC大小，部分样式不显示
![image](https://user-images.githubusercontent.com/38367204/71608229-9449d700-2bba-11ea-93d7-56cceb1be441.png)

**Comment by 88250** [comment]
@Vanessa219 看下是否和 https://github.com/88250/solo/issues/24 类似的问题。
