### ISSUE TITLE
编写新文章界面editor加载不出来，更新也无法解决

### ISSUE THREAD

**Issue by Phantom-John** [88250/solo#250]
写新文章的时候editor加载不出来，上社区查提示让升级到最新版本，回到控制台停止docker，删除镜像，pull最新镜像，仍然是5个月之前的镜像，问题迟迟无法解决
![image](https://user-images.githubusercontent.com/26338528/172753917-6559f742-de80-489e-a79c-90344f7dc725.png)

**Comment by 88250** [comment]
https://hub.docker.com/r/b3log/solo

![image](https://user-images.githubusercontent.com/873584/172754041-3d5d7e2a-a5ae-452a-8ca0-d75a174ac5c3.png)
