### ISSUE TITLE
请问支持以markdown文件存储？

### ISSUE THREAD

**Issue by cqboyone** [88250/solo#257]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
1.解偶，markdown文件兼容性好，以后想换其他工具方便。
2.文档提交github方便查看变更内容。
3.markdown文件方便同步、备份、转移。
4.目前是typora写文档，onedrive同步到云端，群晖每天备份onedrive上面的文档，同时上传文档到github。如果支持以markdown文件保存，可以替换掉typora。

### 描述最优的解决方案 Describe the optimal solution
1.数据存储增加markdown文件存储。

**Comment by 88250** [comment]
不支持，但是可以导出 Markdown。
