### ISSUE TITLE
所见即所得加粗问题

### ISSUE THREAD

**Issue by AlgerFan** [88250/solo#26]
所见即所得加粗字体中包含标点符号时，再编辑其他地方，这时会出现加粗失效的问题
![image](https://user-images.githubusercontent.com/38367204/71637795-4c918100-2c88-11ea-937c-40e14bb62835.png)

**Comment by AlgerFan** [comment]
刚又试了下源码模式，加粗包含标点符号时，确实不起效

**Comment by 88250** [comment]
加粗、强调的 Markdown 规范[非常复杂](https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis)，Vditor 是完全遵循该规范的，所以会出现这个情况。

**Comment by AlgerFan** [comment]
好的，明白

**Comment by 88250** [comment]
感谢帮忙测试反馈，如果发现其他问题请继续跟帖，谢谢！
