### ISSUE TITLE
博客在个人网站更新之后，点击同步到社区没有效果，社区的博客内容还是更新之前的

### ISSUE THREAD

**Issue by Leif160519** [88250/solo#265]
### 描述问题 Describe the problem
博客在个人网站更新之后，点击同步到社区没有效果，社区的博客内容还是更新之前的

### 期待的结果 Expected result

博客更新过后点击同步到社区，社区上能同步更新

### 截屏或录像 Screenshot or video

个人博客的内容：https://github.icu/articles/2023/06/10/1686364528354.html
![image](https://github.com/88250/solo/assets/19452903/ec91c6c3-bc35-49ed-8d93-7211ff878d40)
社区同步的内容：https://ld246.com/article/1686364532507
![image](https://github.com/88250/solo/assets/19452903/6564c93b-20a1-4fa3-80d1-d6240a2009a1)

### 版本环境 Version environment

* 版本 Version：4.4.0
* 操作系统 Operating system：ubuntu 20.04 docker部署
* 浏览器 Browser：chrome

**Comment by Leif160519** [comment]
知道原因了，要积分的￣へ￣
![image](https://github.com/88250/solo/assets/19452903/0ce0442b-b41e-4ba5-b780-952825f6d557)
如果推送的时候能给个页面上的提示就好了

**Comment by 88250** [comment]
感谢反馈，我们目前暂时没有时间改进 Solo，欢迎贡献代码。
