### ISSUE TITLE
导入 Markdown ZIP 文件时，报错：invalid CEN header (bad entry name)

### ISSUE THREAD

**Issue by YoungYo** [88250/solo#266]
后台报错：java.util.zip.ZipException: invalid CEN header (bad entry name)
前端截图：
![image](https://github.com/88250/solo/assets/19580745/3d7bffe8-ed9d-4aa8-9581-998ad10b52ae)
我要上传的文件：
[ARP.zip](https://github.com/88250/solo/files/11990884/ARP.zip)

我的运行平台是Win10

**Comment by 88250** [comment]
大概是不支持该压缩包吧，请重新压缩后再试试。
