### ISSUE TITLE
arm版本docker包

### ISSUE THREAD

**Issue by zhiqiang0819** [88250/solo#267]
### 你在什么场景下需要该功能？ In what scenarios do you need this function?
在树莓派上拉取docker 镜像，发现包是amd64的，无法运行

在树莓派上拉取docker 镜像，发现包是amd64的，无法运行

### 描述最优的解决方案 Describe the optimal solution
做一个arm 64的镜像

**Comment by 88250** [comment]
Duplicate of https://github.com/88250/solo/issues/222
