### ISSUE TITLE
登录出现401错误

### ISSUE THREAD

**Issue by wenyl** [88250/solo#275]
用的docker镜像，一直都正常的，今天下午显示出现获取文件凭证失败，上传的图片文件路径很长导致博客无法保存
![image](https://github.com/88250/solo/assets/24486381/3f6c40c0-73aa-4aca-b96a-82661e82d5d5)

然后退出重新登录就一直提示
401 Unauthorized!
这是后台报错
![image](https://github.com/88250/solo/assets/24486381/7b33764b-f9b8-47f1-afc7-8849fdbaf813)
启动源码调试报错内容为
![image](https://github.com/88250/solo/assets/24486381/d57aff70-6831-4899-a389-329669826894)

**Comment by 88250** [comment]
这几天攻击太多，改进了一些拦截规则导致的，目前已经修复，感谢反馈。
