### ISSUE TITLE
应国家要求整改

### ISSUE THREAD

**Issue by dengzy007hi** [88250/solo#28]
用了很久了啊，昨天已经接到整改通知，望开发者也知道这个事情，主要是两个功能要弄。
1.  评论： 个人网站，即使有这俩字都不可以的，功能更不行。
2.  网站备案号： 需要链接到公安部备案查询结果页。 不链接也不行。
通知我7天整改，否则注销备案，这个很无奈啊。。。

**Comment by 88250** [comment]
谢谢告知，ICP 个人备案现在确实抓得非常紧，不只是`评论`了，个人备案连`博客`两字也是不允许的，所以这其实不是程序问题，作为作者我也很无奈……

社区讨论帖 https://hacpai.com/article/1577959818909
