### ISSUE TITLE
只判断电脑版皮肤是否存在，没有判断移动版

### ISSUE THREAD

**Issue by adlered** [88250/solo#30]
如果移动版皮肤不存在，则直接报错，不会自动修改。

具体发生位置和修改方案请 D 哥 [移步到这里](https://github.com/AdlerED/bolo-solo/issues/21)

**Comment by 88250** [comment]
感谢，我稍微调整了一下你提供的解决方案，分开判断比较好一些。

**Comment by adlered** [comment]
分开判断比较好，借走啦 :smile:
