### ISSUE TITLE
移动端所见即所得编辑两侧留白过多问题

### ISSUE THREAD

**Issue by AlgerFan** [88250/solo#31]
所见即所得没有之前好用了，问题是手机大小/手机端编辑器两侧空白较多，昨天还没有这个情况，今天更新后才出现的。
![image](https://user-images.githubusercontent.com/38367204/71716620-52d25980-2e50-11ea-943d-74f8071c0f31.png)

**Comment by 88250** [comment]
嗯，我们也注意到了，稍后修复。
