### ISSUE TITLE
皮肤 Casper 标签页标题显示异常

### ISSUE THREAD

**Issue by ellenbboe** [88250/solo#43]
点图片进入 标签页显示的是地址
点标题进入 显示的是标题
:)

**Comment by Vanessa219** [comment]
没找到从哪里可以点击图片进入标签页？ 😅

**Comment by ellenbboe** [comment]
> 没找到从哪里可以点击图片进入标签页？ 😅

就是点配图那块区域进入文章 :)

**Comment by ellenbboe** [comment]
![image](https://user-images.githubusercontent.com/24969128/72491535-476e2d80-3855-11ea-9ca0-d3d0b5990f69.png)
