### ISSUE TITLE
评论插件点击之后自动关闭

### ISSUE THREAD

**Issue by zeekling** [88250/solo#48]
重现博客地址:[ZEEKLING](https://www.zeekling.cn/), 浏览器google

重现步骤:
1. 随便点击一篇博客并且点击评论,如下图所示,显示正常
![2020-01-18_20-22.png](https://img.zeekling.cn/images/2020/01/18/2020-01-18_20-22.png)
2. 回到首页,点击另一篇文章,点击评论,评论页面就会自动弹出评论框并且自动关闭.

但是刷新缓存(ctrl + F5)之后就OK了,再次点击另一篇文章的评论就又重现了.

**Comment by 88250** [comment]
我这里重现不了哦，麻烦录个 gif 看下，谢谢。

**Comment by 88250** [comment]
另外，你更新一下镜像再试，最近几天调整比较大。

**Comment by zeekling** [comment]
![vokoscreen-2020-01-18_21-04-31.gif](https://img.zeekling.cn/images/2020/01/18/vokoscreen-2020-01-18_21-04-31.gif)

**Comment by zeekling** [comment]
> 另外，你更新一下镜像再试，最近几天调整比较大。

就是最近两天跟新的.

**Comment by 88250** [comment]
再更新一下，刚刚推送了一次镜像发布。

**Comment by zeekling** [comment]
跟新了,还是存在.

**Comment by 88250** [comment]
好的，可以重现了。稍后解决，感谢反馈。

**Comment by zeekling** [comment]
> 好的，可以重现了。稍后解决，感谢反馈。

好的,辛苦.
