### ISSUE TITLE
Pinghsu 皮肤 footer.ftl 存在错误 script 标签

### ISSUE THREAD

**Issue by 9526xu** [88250/solo#50]
Pinghsu 皮肤 footer.ftl 第 86 行存在错误 script 标签。
![image](https://user-images.githubusercontent.com/15943801/72703299-2f1d4c00-3b90-11ea-9b28-bc46b8d153c8.png)

结合当前代码，此处 script 标签需要被移除。

**Comment by 88250** [comment]
谢谢。

**Comment by 9526xu** [comment]
哈哈 很高兴，第一次参加了开源项目。
