### ISSUE TITLE
使用发布的源码安装solo提示没有webapp路径

### ISSUE THREAD

**Issue by cloudstaymoon** [88250/solo#56]
Failed to execute goal org.mortbay.jetty:maven-jetty-plugin:6.1.26:run (default-cli) on project solo: Webapp source directory /******/solo-3.8.0/src/main/webapp does not exist -> [Help 1]

**Comment by 88250** [comment]
Solo 最新版没有使用 Servlet 容器，请参考 [Solo 从设计到实现](https://hacpai.com/article/1537690756242) 进行搭建。

**Comment by zhaoliangwan** [comment]
D大，使用源码部署，使用mvn打包以后 java -cp "lib/*:." org.b3log.solo.Server 运行会提示找不到这个类，是否只能通过docker部署solo呢？

**Comment by zhaoliangwan** [comment]
# java -cp "lib/*:." org.b3log.solo.Server
Error: Could not find or load main class org.b3log.solo.Server
Caused by: java.lang.ClassNotFoundException: org.b3log.solo.Server

**Comment by cloudstaymoon** [comment]
D大，我使用docker部署后也提示Latke 配置错误，前端控制台报错为：
GET http://********:8080/scss/start.css?1580740935422 net::ERR_CONNECTION_REFUSED
(index):39 GET http://********:8080/js/lib/qrious.min.js net::ERR_CONNECTION_REFUSED
请问该怎么解决啊？我快被Latke折磨死了T^T

**Comment by cloudstaymoon** [comment]
我目前的搭建方式是一台服务器做Nginx，另一台做应用服务器，但是无论源码mvn编译部署还是docker部署都会出现Latke配置错误，还烦请D大抽空帮忙解答一下~   T^T

**Comment by 88250** [comment]
请看 [Latke 配置剖析](https://hacpai.com/article/1474087427032)。

**Comment by cloudstaymoon** [comment]
刚刚重新启动了一下solo，需要将server端口改为80端口才能读取到静态资源，目前已解决，成功加入b3log大家庭，感谢D大~
