### ISSUE TITLE
提供 API

### ISSUE THREAD

**Issue by Vanessa219** [88250/solo#6]
### 需求原因

想写一个小程序博客，数据来源于使用 solo 搭建的个人博客系统里面的文章。

### 其他博客系统的功能

发现 wordpress 和其他博客系统实现了个人博客更新文章可以同步到小程序上。
比如：
1. https://github.com/aquanlerou/WeHalo
2. https://github.com/iamxjb/winxin-app-watch-life.net
3. https://github.com/CavinCao/mini-blog

### 具体功能

1. 文章列表
2. 文章搜索功能
3. 标签
4. 分类
5. 文章配图缩略图
6. 文章阅读原文链接为个人博客详细地址

**Comment by 88250** [comment]
暂时关闭，先完成 v4 静态化。

**Comment by zeekling** [comment]
API 什么时候能提供出来.

**Comment by 88250** [comment]
> API 什么时候能提供出来.

目前暂时没有这方面的计划；如果你有空的话欢迎贡献代码。

**Comment by zeekling** [comment]
最近换工作,不一定有时间,先看看吧.

**Comment by 88250** [comment]
@lzh984294471 嗯，祝你一切顺利。
