### ISSUE TITLE
最新solo镜像，前端页面排版错误

### ISSUE THREAD

**Issue by Leif160519** [88250/solo#62]
![image](https://user-images.githubusercontent.com/19452903/74105967-65e9ef00-4b9d-11ea-8a8d-b517196ba827.png)
手机上也是如此

**Comment by Leif160519** [comment]
点击任意连接都跳转到127.0.0.1:8080/xxxxxx

**Comment by 88250** [comment]
https://hacpai.com/article/1580877736555

**Comment by Leif160519** [comment]
我的nginx不在docker中，而且我用的计划任务每个周日更新，为啥会突然出现这种情况呢，nginx配置还是之前的

**Comment by Leif160519** [comment]
![image](https://user-images.githubusercontent.com/19452903/74115797-c6078200-4beb-11ea-9ab8-d9256e25f118.png)
加上header参数就可以了，不知道最新镜像更新了啥，之前没加都是可以的

**Comment by 88250** [comment]
> ![image](https://user-images.githubusercontent.com/19452903/74115797-c6078200-4beb-11ea-9ab8-d9256e25f118.png)
> 加上header参数就可以了，不知道最新镜像更新了啥，之前没加都是可以的

https://github.com/88250/solo/issues/58
