### ISSUE TITLE
Too Many Requests 问题

### ISSUE THREAD

**Issue by zeekling** [88250/solo#63]
今天我博客又出现了Too Many Requests，我看了nginx日志，并没有受到攻击。
能不能把这个限制加到solo博客里面，不要通过社区，通过社区耦合性太强了，并且每个博客访问量不一致，通过社区不好控制。

**Comment by 88250** [comment]
麻烦提供一下你的 IP。

**Comment by zeekling** [comment]
服务器的嘛

**Comment by 88250** [comment]
客户端的。

**Comment by zeekling** [comment]
124.152.204.129

**Comment by 88250** [comment]
IP 已经解封，稍后再继续调整一下限流 。主要是最近几天社区持续被每秒 30-50 个请求攻击着，所以限流比较紧一些。
