### ISSUE TITLE
博客编辑界面开启全屏后不会自动关闭

### ISSUE THREAD

**Issue by Camliar** [88250/solo#69]
### 问题描述
博客版本： 3.9.0
在新建文章或编辑已有文章时，如果打开了全屏编辑， 如果不写内容 退出或者不保存退出的话，然后再重新进入草稿的编辑界面还是新建文章界面还是全屏状态。

### 重现过程
1. 打开新增文章界面，点击全屏；
2. 不写任何内容，点击浏览器返回按钮退出；
3. 再进入文章编辑界面，还是全屏状态

**Comment by Vanessa219** [comment]
后台采用了缓存机制，不会刷新页面。因此进入到该页面还是维持原有的状态，点击取消全屏或使用[快捷键](https://hacpai.com/article/1582778815353) 关闭即可

**Comment by Camliar** [comment]
ok，这样操作是没问题，就是体验感觉不是很好。

**Comment by Camliar** [comment]
> 后台采用了缓存机制，不会刷新页面。因此进入到该页面还是维持原有的状态，点击取消全屏或使用[快捷键](https://hacpai.com/article/1582778815353) 关闭即可

ok，这样操作是没问题，就是体验感觉不是很好。

**Comment by 88250** [comment]
感谢反馈，先这样吧，我关闭了。
