### ISSUE TITLE
编辑器加载失败

### ISSUE THREAD

**Issue by yuyedaidao** [88250/solo#72]
Uncaught ReferenceError: Vditor is not defined

![image](https://user-images.githubusercontent.com/6354958/75868173-a0fcdc80-5e42-11ea-9453-7d6304cfff3b.png)

**Comment by 88250** [comment]
如果不是最新版的话请更新到最新版。

**Comment by yuyedaidao** [comment]
更新后可以了，多谢。前几天刚更新了，还是没跟上进度
