### ISSUE TITLE
一些小建议和反馈

### ISSUE THREAD

**Issue by imsancn** [88250/solo#73]
- 升级最新版本后发现后台管理，点击左侧菜单无法正常刷新右侧内容，需要全局刷新浏览器，才能显示右侧内容，不清楚是不是升级导致的异常。
- 建议在[用户管理]增加用户在hacpai.com的昵称字段
- 建议增加配置项，用昵称替代全局的author显示，比如文章作者，签名等处

**Comment by 88250** [comment]
请检查你引入的脚本，比如公告栏、页脚位置；昵称这部分暂时不打算动了，因为只有用户名是唯一的，使用昵称问题会比较多，感谢反馈。

**Comment by imsancn** [comment]
> 请检查你引入的脚本，比如公告栏、页脚位置；昵称这部分暂时不打算动了，因为只有用户名是唯一的，使用昵称问题会比较多，感谢反馈。
检查了下的确是去掉
APlayer.min.js的引用就ok了，有其他背景音乐播放器可以用吗
