### ISSUE TITLE
不同域名，同一个服务器，显示的统计数据不一致

### ISSUE THREAD

**Issue by Leif160519** [88250/solo#76]
带www和不带www的域名，显示的统计内容有区别：

不带www
![image](https://user-images.githubusercontent.com/19452903/76376805-37ba2380-6384-11ea-9a0f-c3613d10e7f2.png)
![image](https://user-images.githubusercontent.com/19452903/76376844-4d2f4d80-6384-11ea-819a-4e16bda9e733.png)

带www
![image](https://user-images.githubusercontent.com/19452903/76376865-5d472d00-6384-11ea-91f4-da7e0b6577c4.png)
![image](https://user-images.githubusercontent.com/19452903/76376883-6932ef00-6384-11ea-9132-972833f736a6.png)

不懂是什么原因导致的统计数据的差别

而且，刷新不带www的网址时，底部数据会先显示带www的统计数据之后更新为不带www的统计数据，比如说不带www的浏览量为100，带www的为50，刷新不带www的网址时，先显示50的浏览量，然后立即变为100的浏览量

**Comment by 88250** [comment]
Solo 使用社区统一提供的统计组件 [uvstat](https://github.com/Vanessa219/uvstat) 实现访问计数，该服务的原理是通过 URL 作为 key 进行统计的，所以不同 URL 会分开独立统计。

建议博客端统一使用一个域名，比如将 www 二级域名通过 301 重定向到不带 www 的域名上。

**Comment by Leif160519** [comment]
> Solo 使用社区统一提供的统计组件 [uvstat](https://github.com/Vanessa219/uvstat) 实现访问计数，该服务的原理是通过 URL 作为 key 进行统计的，所以不同 URL 会分开独立统计。
> 
> 建议博客端统一使用一个域名，比如将 www 二级域名通过 301 重定向到不带 www 的域名上。

这个问题我后来在nginx中解决了，设置了301重定向。


另外问下，某次更新solo镜像之后，页面右下角的评论数不显示了，是去掉了吗

**Comment by 88250** [comment]
是的，去掉了总评论数。
