### ISSUE TITLE
可能是由于鄙人在黑客派的聊天室发言过多，导致自动被封禁

### ISSUE THREAD

**Issue by devcui** [88250/solo#85]
### 描述问题

今巳时于众言堂言多矣,致封禁矣,今无以入 

### 期待的结果

今能以入 

### 其他信息

吾之账簿细观其间,现一行阿拉伯字母名曰:ferried

**Comment by 88250** [comment]
你在说的啥哟 😂 没人封禁你账号啊。

**Comment by adlered** [comment]
D哥我要举报，他扫黑客派，被banip了

**Comment by devcui** [comment]
?当我打出问号的时候

**Comment by anyshift** [comment]
D哥我要举报，他扫黑客派，被风控了

**Comment by devcui** [comment]
我没有，我不是

**Comment by adlered** [comment]
我妈说，做事要做绝
[Screenshot_2020-03-26-10-15-18-416_com.tencent.mobileqq.jpg](https://pic.stackoverflow.wiki/uploadImages/124/64/16/42/2020/03/26/10/15/c3a5f117-8de9-47bf-991e-b4c2f83e1877.jpg)

**Comment by 88250** [comment]
@ferried 发邮件到 support@b3log.org，附上 IP
