### ISSUE TITLE
废弃评论推送社区接口

### ISSUE THREAD

**Issue by 88250** [88250/solo#89]
* https://rhythm.b3log.org/api/comment 该接口将下线
* 停止社区端回帖推送博客端

社区评论接入完全由 [vcomment](https://github.com/Vanessa219/vcomment) 组件实现。

**Comment by adlered** [comment]
文章接口保留吗

**Comment by 88250** [comment]
> 文章接口保留吗

保留的，[社区内容交互接口文档](https://hacpai.com/article/1457158841475)已经更新。
