### ISSUE TITLE
nginx方向代理多台solo服务登录时出现404错误

### ISSUE THREAD

**Issue by dinglevin** [88250/solo#90]
nginx配置：
`# blog.server1
upstream blog.server {
    server blog-server1:8080;
    server blog-server2:8080;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

server{
    listen 80;
    server_name dinglevin.tech;
    access_log  /var/log/nginx/blog_server_access.log;

    location / {
        proxy_pass http://blog.server$request_uri;

        proxy_cookie_path ~*^/.* /;
        proxy_http_version 1.1;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        client_max_body_size  10m;
    }

     location ~ .*\.(js|css)$ {
         proxy_pass http://blog.server;

         proxy_set_header  Host $http_host;
         proxy_set_header  X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto https;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
         client_max_body_size  10m;
     }
}

server{
    listen 80;
    server_name 182.92.126.122;
    access_log  /var/log/nginx/blog_server_access.log;

    location / {
        proxy_pass http://blog.server$request_uri;

        proxy_cookie_path ~*^/.* /;
        proxy_http_version 1.1;
        proxy_set_header  Host $http_host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        client_max_body_size  10m;
    }

    location ~ .*\.(js|css)$ {
         proxy_pass http://blog.server;

         proxy_set_header  Host $http_host;
         proxy_set_header  X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto https;
         proxy_set_header Upgrade $http_upgrade;
         proxy_set_header Connection $connection_upgrade;
         client_max_body_size  10m;
    }
}`

![image](https://user-images.githubusercontent.com/1655965/78040785-7c911300-73a2-11ea-94ed-4fc2d177f7d6.png)

![image](https://user-images.githubusercontent.com/1655965/78040824-8d418900-73a2-11ea-86f0-1e51a9c0463e.png)

只启动一台solo服务时没问题

**Comment by 88250** [comment]
你好，Solo 不支持集群，感谢反馈。
