### ISSUE TITLE
访问量及文章浏览量问题

### ISSUE THREAD

**Issue by 923012373** [88250/solo#92]
访问量一会60+,一会100+。文章浏览量也是。

**Comment by 88250** [comment]
第一个值是以前默认的，异步加载后获取到最新的，所以看上去会“闪”一下。

**Comment by 923012373** [comment]
不是'闪一下'诶是加载完的情况

**Comment by 88250** [comment]
我不是太明白，麻烦录个 gif。

**Comment by 923012373** [comment]
![image](https://user-images.githubusercontent.com/33079824/78419899-e3514d80-767c-11ea-9777-764306d311d2.png)
![image](https://user-images.githubusercontent.com/33079824/78419920-0bd94780-767d-11ea-8d8a-85af1058f3cb.png)

**Comment by 88250** [comment]
第一个截图和第二个截图的 URL 是一样的么？麻烦发出来我看下。

**Comment by 923012373** [comment]
是这样的， 我发现是从微信、扣扣我发的说说的这个链接里点进去和直接从浏览器点进去访问量是不一样的，微信扣扣点击链接是看不到url的。我的博客地址是hailangjiang.top,你可以看一下，这两张图是来自同一个博客。

**Comment by 88250** [comment]
你好，我用你博客 URL `https://www.hailangjiang.top`  访问，PC 端 Chrome 和移动端 QQ 的结果是一致的：

![QQ截图20200404171637](https://user-images.githubusercontent.com/873584/78423517-6b455080-7699-11ea-9394-bd634f8c5068.jpg)
![QQ截图20200404172007](https://user-images.githubusercontent.com/873584/78423522-6f716e00-7699-11ea-921e-3a0b5e07c7d0.jpg)

**Comment by 923012373** [comment]
吐血。。。你看这是我现在的访问结果





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"D"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 下午5:27
收件人:&nbsp;"88250/solo"<solo@noreply.github.com&gt;;
抄送:&nbsp;"何谓致死不渝"<923012373@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [88250/solo] 访问量及文章浏览量问题 (#92)





 
你好，我用你博客 URL https://www.hailangjiang.top  访问，PC 端 Chrome 和移动端 QQ 的结果是一致的：

**Comment by 88250** [comment]
复制 URL 用 PC 端 QQ 的“发送到手机”后再手机打开试试？

**Comment by 923012373** [comment]
你看这样也有问题，甚至当前访客跳到9了








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"D"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 下午5:34
收件人:&nbsp;"88250/solo"<solo@noreply.github.com&gt;;
抄送:&nbsp;"何谓致死不渝"<923012373@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [88250/solo] 访问量及文章浏览量问题 (#92)





 
复制 URL 用 PC 端 QQ 的“发送到手机”后再手机打开试试？

**Comment by 88250** [comment]
访客统计是 9 应该没问题吧。

**Comment by 923012373** [comment]
这两行代码我都加了，之前没加报错了。
我在微信和扣扣点击链接，访问量确实就和直接浏览器访问显示的访问量不一样，你可以去我空间点一下看看。QQ：923012373.
proxy_set_header  Host $http_host; proxy_set_header  X-Real-IP $remote_addr;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"D"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 下午5:40
收件人:&nbsp;"88250/solo"<solo@noreply.github.com&gt;;
抄送:&nbsp;"何谓致死不渝"<923012373@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [88250/solo] 访问量及文章浏览量问题 (#92)





 
访客统计请看下用户指南 FAQ 部分。

**Comment by 88250** [comment]
问题最终定位：`https://hailangjiang.top` 和 `https://www.hailangjiang.top` 是两个不同的统计项，所以计数不同。
解决方案：将其中一个重定向到另一个上，建议用和 `server_host` 相同的。
