### ISSUE TITLE
add mariadb jdbc dependency

### ISSUE THREAD

**Issue by laoLiangLoveProgram** [88250/solo#96]
### 你在什么场景下需要该功能？

服务器上用的是 mariadb 数据库， 再加个 mysql 内存不太够用， 请求加入 mariadb 的jdbc 的依赖支持， 免得要修改源码才能够运行

### 描述可能的解决方案

加入 mariadb-jdbc 的依赖即可

**Comment by 88250** [comment]
你好，引入该依赖的话会对现有 MySQL 支持产生影响吗？

**Comment by laoLiangLoveProgram** [comment]
不影响吧，就是链接的数据库不一样而已，现在我也才刚入门这个，具体功能还没测试过

**Comment by 88250** [comment]
如果方便的话请帮忙测试并 PR 代码，谢谢。

**Comment by laoLiangLoveProgram** [comment]
最近比较忙， 如果有空， 我会提交一个PR， 当然， 作者要是有闲更新的话， 皆大欢喜

**Comment by 88250** [comment]
抱歉，我没时间啊 😂 
问题我先关闭了，你有空 PR 就行。
