### ISSUE TITLE
maven WARNING and docker build faild

### ISSUE THREAD

**Issue by baoroushi** [88250/solo#97]
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (maven build)
[Pipeline] echo
maven build
[Pipeline] sh
+ export JAVA_HOME=/usr/local/openjdk-8
+ /usr/local/apache-maven-3.6.3/bin/mvn clean package -Dmaven.test.skip=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.b3log:solo:jar:4.0.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 311, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ---------------------------< org.b3log:solo >---------------------------
[INFO] Building Solo 4.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ solo ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (prepare-agent) @ solo ---
[INFO] argLine set to -javaagent:/opt/maven/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/jenkins/agent/workspace/test-pipline2/target/jacoco.exec
[INFO] 
[INFO] --- license-maven-plugin:3.0:format (default) @ solo ---
[INFO] Updating license headers...
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ solo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 716 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ solo ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 147 source files to /home/jenkins/agent/workspace/test-pipline2/target/classes
[WARNING] /home/jenkins/agent/workspace/test-pipline2/src/main/java/org/b3log/solo/util/Markdowns.java: /home/jenkins/agent/workspace/test-pipline2/src/main/java/org/b3log/solo/util/Markdowns.java使用或覆盖了已过时的 API。
[WARNING] /home/jenkins/agent/workspace/test-pipline2/src/main/java/org/b3log/solo/util/Markdowns.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[WARNING] /home/jenkins/agent/workspace/test-pipline2/src/main/java/org/b3log/solo/processor/TagProcessor.java: 某些输入文件使用了未经检查或不安全的操作。
[WARNING] /home/jenkins/agent/workspace/test-pipline2/src/main/java/org/b3log/solo/processor/TagProcessor.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ solo ---
[INFO] Not copying test resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ solo ---
[INFO] Not compiling test sources
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ solo ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ solo ---
[INFO] Building jar: /home/jenkins/agent/workspace/test-pipline2/target/solo.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (make-assembly) @ solo ---
[INFO] Reading assembly descriptor: src/assembly/bin.xml
[INFO] Copying files to /home/jenkins/agent/workspace/test-pipline2/target/solo
**[WARNING] Assembly file: /home/jenkins/agent/workspace/test-pipline2/target/solo is not a regular file (it may be a directory). It cannot be attached to the project build for installation or deployment.**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.978 s
[INFO] Finished at: 2020-04-08T11:42:21+08:00
[INFO] ------------------------------------------------------------------------
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (docker build and push images)
[Pipeline] echo
docker build and push images
[Pipeline] sh
+ REPOSITORY=local.harbor/library/solo:1.0.2
+ echo local.harbor/library/solo:1.0.2
local.harbor/library/solo:1.0.2
+ cat
+ docker build -t local.harbor/library/solo:1.0.2 .
Sending build context to Docker daemon    116MB

Step 1/6 : FROM local.harbor/library/tomcat:latest
 ---> e36064f7c6f0
Step 2/6 : RUN rm -rf /usr/local/tomcat/webapps/ROOT/
 ---> Using cache
 ---> 4cf6eeca2866
**Step 3/6 : COPY target/*.war /usr/local/tomcat/webapps/ROOT.war
COPY failed: no source files were specified**
[Pipeline] }

**Comment by 88250** [comment]
maven WARNING 请暂时忽略；docker 镜像没有 war 包，请参考 Dockerfile。
